[package]
name = "cp_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# formal-power-series = { path = "../cprs/crates/polynomial/formal-power-series" }
modint = { path = "../cprs/crates/number-theory/modint" }
combination = { path = "../cprs/crates/number-theory/combination" }
# proconio = "0.5.0"
